system/kvm: Expose kvm_irqchip_[add,remove]_change_notifier()
Currently kvm_irqchip_add_irqfd_notifier() and
kvm_irqchip_remove_irqfd_notifier() are only declared on
target specific code. There is not particular reason to,
as their prototypes don't use anything target related.

Move their declaration with common prototypes, otherwise
the next commit would trigger:

  hw/vfio/pci.c: In function ‘vfio_realize’:
  hw/vfio/pci.c:3178:9: error: implicit declaration of function ‘kvm_irqchip_add_change_notifier’
   3178 |         kvm_irqchip_add_change_notifier(&vdev->irqchip_change_notifier);
        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        |         kvm_irqchip_add_irqfd_notifier
  hw/vfio/pci.c:3236:9: error: implicit declaration of function ‘kvm_irqchip_remove_change_notifier’
   3236 |         kvm_irqchip_remove_change_notifier(&vdev->irqchip_change_notifier);
        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        |         kvm_irqchip_remove_irqfd_notifier

Reviewed-by: Pierrick Bouvier <pierrick.bouvier@linaro.org>
Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Reviewed-by: Richard Henderson <richard.henderson@linaro.org>
Link: https://lore.kernel.org/qemu-devel/20250308230917.18907-9-philmd@linaro.org
Signed-off-by: Cédric Le Goater <clg@redhat.com>